name: CI Pipeline

on:
  push:
    branches: [ main ]  # Adjust if your default branch is 'master'

jobs:
  build-and-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build with Make
      run: make

    - name: Install to temporary directory
      run: make install DESTDIR=./install

    - name: Verify installed files
      run: ls ./install/bin/iio_fm_radio ./install/bin/iio_fm_radio_play
