name: CI Pipeline

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch

jobs:
  build-and-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checkout repository code

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential  # Install compiler tools

    - name: Build with Make
      run: make  # Compile the project

    - name: Install to temporary directory
      run: |
        # Install to local directory to avoid system modifications
        make install DESTDIR=./install

    - name: Verify installed files
      run: |
        echo "Starting installation verification..."
        
        # Check for main executable
        if [ -f "./install/bin/iio_fm_radio" ]; then
          echo "✓ iio_fm_radio found in bin directory"
        else
          echo "❌ Error: iio_fm_radio not installed!"
          exit 1  # Fail the CI if missing
        fi

        # Check for play script
        if [ -f "./install/bin/iio_fm_radio_play" ]; then
          echo "✓ iio_fm_radio_play found in bin directory"
        else
          echo "❌ Error: iio_fm_radio_play not installed!"
          exit 1  # Fail the CI if missing
        fi

        echo "✅ All files verified successfully"
